// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr811Rz8CFUhxBpARTXgdzg3TB2QV8oeg',
    appId: '1:774885901566:web:7b5e9aa767f25064bf11af',
    messagingSenderId: '774885901566',
    projectId: 'dentalplaza-376d3',
    authDomain: 'dentalplaza-376d3.firebaseapp.com',
    storageBucket: 'dentalplaza-376d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAttQJSTPAHKb3X9pngVwq_9YrCCfBMfME',
    appId: '1:774885901566:android:fa1f235b05de15dbbf11af',
    messagingSenderId: '774885901566',
    projectId: 'dentalplaza-376d3',
    storageBucket: 'dentalplaza-376d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPApEUpzD7PdyEdIXdl_td6U5ZF9hyFFc',
    appId: '1:774885901566:ios:853f95b86dc7c9b9bf11af',
    messagingSenderId: '774885901566',
    projectId: 'dentalplaza-376d3',
    storageBucket: 'dentalplaza-376d3.appspot.com',
    iosClientId: '774885901566-e87arniubomgq93n8dt5525nfmcuhv5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPApEUpzD7PdyEdIXdl_td6U5ZF9hyFFc',
    appId: '1:774885901566:ios:853f95b86dc7c9b9bf11af',
    messagingSenderId: '774885901566',
    projectId: 'dentalplaza-376d3',
    storageBucket: 'dentalplaza-376d3.appspot.com',
    iosClientId: '774885901566-e87arniubomgq93n8dt5525nfmcuhv5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
